# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  save: keybase encrypt circleoncircles -i .streamlit/secrets.toml -o .streamlit/secrets.toml.encrypted
  load: keybase decrypt circleoncircles -i .streamlit/secrets.toml.encrypted -o .streamlit/secrets.toml